version: '3'
services:
  simplesynth:
    build:
      context: .
    ports:
      - "2222:22"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /usr/sbin/sshd -D